In [1]:
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np
import seaborn as sns
plt.style.use('ggplot')

In [2]:
df = pd.read_csv('sonar.csv')

In [3]:
df.head()

,Freq_1,Freq_2,Freq_3,Freq_4,Freq_5,Freq_6,Freq_7,Freq_8,Freq_9,Freq_10,...,Freq_52,Freq_53,Freq_54,Freq_55,Freq_56,Freq_57,Freq_58,Freq_59,Freq_60,Label
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
df.tail()

,Freq_1,Freq_2,Freq_3,Freq_4,Freq_5,Freq_6,Freq_7,Freq_8,Freq_9,Freq_10,...,Freq_52,Freq_53,Freq_54,Freq_55,Freq_56,Freq_57,Freq_58,Freq_59,Freq_60,Label
203,0.0187,0.0346,0.0168,0.0177,0.0393,0.1630,0.2028,0.1694,0.2328,0.2684,...,0.0116,0.0098,0.0199,0.0033,0.0101,0.0065,0.0115,0.0193,0.0157,M
204,0.0323,0.0101,0.0298,0.0564,0.0760,0.0958,0.0990,0.1018,0.1030,0.2154,...,0.0061,0.0093,0.0135,0.0063,0.0063,0.0034,0.0032,0.0062,0.0067,M
205,0.0522,0.0437,0.0180,0.0292,0.0351,0.1171,0.1257,0.1178,0.1258,0.2529,...,0.0160,0.0029,0.0051,0.0062,0.0089,0.0140,0.0138,0.0077,0.0031,M
206,0.0303,0.0353,0.0490,0.0608,0.0167,0.1354,0.1465,0.1123,0.1945,0.2354,...,0.0086,0.0046,0.0126,0.0036,0.0035,0.0034,0.0079,0.0036,0.0048,M
207,0.0260,0.0363,0.0136,0.0272,0.0214,0.0338,0.0655,0.1400,0.1843,0.2354,...,0.0146,0.0129,0.0047,0.0039,0.0061,0.0040,0.0036,0.0061,0.0115,M

In [5]:
df.shape

(208, 61)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Freq_1   208 non-null    float64
 1   Freq_2   208 non-null    float64
 2   Freq_3   208 non-null    float64
 3   Freq_4   208 non-null    float64
 4   Freq_5   208 non-null    float64
 5   Freq_6   208 non-null    float64
 6   Freq_7   208 non-null    float64
 7   Freq_8   208 non-null    float64
 8   Freq_9   208 non-null    float64
 9   Freq_10  208 non-null    float64
 10  Freq_11  208 non-null    float64
 11  Freq_12  208 non-null    float64
 12  Freq_13  208 non-null    float64
 13  Freq_14  208 non-null    float64
 14  Freq_15  208 non-null    float64
 15  Freq_16  208 non-null    float64
 16  Freq_17  208 non-null    float64
 17  Freq_18  208 non-null    float64
 18  Freq_19  208 non-null    float64
 19  Freq_20  208 non-null    float64
 20  Freq_21  208 non-null    float64
 21  Freq_22  208 non-null    float64
 22  Freq_23  208 non-null    float64
 23  Freq_24  208 non-null    float64
 24  Freq_25  208 non-null    float64
 25  Freq_26  208 non-null    float64
 26  Freq_27  208 non-null    float64
 27  Freq_28  208 non-null    float64
 28  Freq_29  208 non-null    float64
 29  Freq_30  208 non-null    float64
 30  Freq_31  208 non-null    float64
 31  Freq_32  208 non-null    float64
 32  Freq_33  208 non-null    float64
 33  Freq_34  208 non-null    float64
 34  Freq_35  208 non-null    float64
 35  Freq_36  208 non-null    float64
 36  Freq_37  208 non-null    float64
 37  Freq_38  208 non-null    float64
 38  Freq_39  208 non-null    float64
 39  Freq_40  208 non-null    float64
 40  Freq_41  208 non-null    float64
 41  Freq_42  208 non-null    float64
 42  Freq_43  208 non-null    float64
 43  Freq_44  208 non-null    float64
 44  Freq_45  208 non-null    float64
 45  Freq_46  208 non-null    float64
 46  Freq_47  208 non-null    float64
 47  Freq_48  208 non-null    float64
 48  Freq_49  208 non-null    float64
 49  Freq_50  208 non-null    float64
 50  Freq_51  208 non-null    float64
 51  Freq_52  208 non-null    float64
 52  Freq_53  208 non-null    float64
 53  Freq_54  208 non-null    float64
 54  Freq_55  208 non-null    float64
 55  Freq_56  208 non-null    float64
 56  Freq_57  208 non-null    float64
 57  Freq_58  208 non-null    float64
 58  Freq_59  208 non-null    float64
 59  Freq_60  208 non-null    float64
 60  Label    208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [7]:
df.isnull().sum()

Freq_1     0
Freq_2     0
Freq_3     0
Freq_4     0
Freq_5     0
          ..
Freq_57    0
Freq_58    0
Freq_59    0
Freq_60    0
Label      0
Length: 61, dtype: int64

In [8]:
df.describe()

,Freq_1,Freq_2,Freq_3,Freq_4,Freq_5,Freq_6,Freq_7,Freq_8,Freq_9,Freq_10,...,Freq_51,Freq_52,Freq_53,Freq_54,Freq_55,Freq_56,Freq_57,Freq_58,Freq_59,Freq_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [9]:
target = df.columns[-1]
features = df.columns[:-1]
target, features

('Label',
 Index(['Freq_1', 'Freq_2', 'Freq_3', 'Freq_4', 'Freq_5', 'Freq_6', 'Freq_7',
        'Freq_8', 'Freq_9', 'Freq_10', 'Freq_11', 'Freq_12', 'Freq_13',
        'Freq_14', 'Freq_15', 'Freq_16', 'Freq_17', 'Freq_18', 'Freq_19',
        'Freq_20', 'Freq_21', 'Freq_22', 'Freq_23', 'Freq_24', 'Freq_25',
        'Freq_26', 'Freq_27', 'Freq_28', 'Freq_29', 'Freq_30', 'Freq_31',
        'Freq_32', 'Freq_33', 'Freq_34', 'Freq_35', 'Freq_36', 'Freq_37',
        'Freq_38', 'Freq_39', 'Freq_40', 'Freq_41', 'Freq_42', 'Freq_43',
        'Freq_44', 'Freq_45', 'Freq_46', 'Freq_47', 'Freq_48', 'Freq_49',
        'Freq_50', 'Freq_51', 'Freq_52', 'Freq_53', 'Freq_54', 'Freq_55',
        'Freq_56', 'Freq_57', 'Freq_58', 'Freq_59', 'Freq_60'],
       dtype='object'))

In [10]:
df[target].value_counts()

Label
M    111
R     97
Name: count, dtype: int64

In [11]:
df.groupby(target).mean()

,Freq_1,Freq_2,Freq_3,Freq_4,Freq_5,Freq_6,Freq_7,Freq_8,Freq_9,Freq_10,...,Freq_51,Freq_52,Freq_53,Freq_54,Freq_55,Freq_56,Freq_57,Freq_58,Freq_59,Freq_60
Label,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [12]:
X = df[features]
Y = df[target]

In [13]:
X, Y

(     Freq_1  Freq_2  Freq_3  Freq_4  Freq_5  Freq_6  Freq_7  Freq_8  Freq_9  \
 0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
 1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
 2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
 3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
 4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
 ..      ...     ...     ...     ...     ...     ...     ...     ...     ...
 203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
 204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
 205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
 206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
 207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

      Freq_10  ...  Freq_51  Freq_52  Freq_53  Freq_54  Freq_55  Freq_56  \
 0     0.2111  ...   0.0232   0.0027   0.0065   0.0159   0.0072   0.0167
 1     0.2872  ...   0.0125   0.0084   0.0089   0.0048   0.0094   0.0191
 2     0.6194  ...   0.0033   0.0232   0.0166   0.0095   0.0180   0.0244
 3     0.1264  ...   0.0241   0.0121   0.0036   0.0150   0.0085   0.0073
 4     0.4459  ...   0.0156   0.0031   0.0054   0.0105   0.0110   0.0015
 ..       ...  ...      ...      ...      ...      ...      ...      ...
 203   0.2684  ...   0.0203   0.0116   0.0098   0.0199   0.0033   0.0101
 204   0.2154  ...   0.0051   0.0061   0.0093   0.0135   0.0063   0.0063
 205   0.2529  ...   0.0155   0.0160   0.0029   0.0051   0.0062   0.0089
 206   0.2354  ...   0.0042   0.0086   0.0046   0.0126   0.0036   0.0035
 207   0.2354  ...   0.0181   0.0146   0.0129   0.0047   0.0039   0.0061

      Freq_57  Freq_58  Freq_59  Freq_60
 0     0.0180   0.0084   0.0090   0.0032
 1     0.0140   0.0049   0.0052   0.0044
 2     0.0316   0.0164   0.0095   0.0078
 3     0.0050   0.0044   0.0040   0.0117
 4     0.0072   0.0048   0.0107   0.0094
 ..       ...      ...      ...      ...
 203   0.0065   0.0115   0.0193   0.0157
 204   0.0034   0.0032   0.0062   0.0067
 205   0.0140   0.0138   0.0077   0.0031
 206   0.0034   0.0079   0.0036   0.0048
 207   0.0040   0.0036   0.0061   0.0115

 [208 rows x 60 columns],
 0      R
 1      R
 2      R
 3      R
 4      R
       ..
 203    M
 204    M
 205    M
 206    M
 207    M
 Name: Label, Length: 208, dtype: object)

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.1, stratify=Y, random_state=1)
X_train.shape, X_test.shape

((187, 60), (21, 60))

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [16]:
model.fit(X_train, Y_train)

LogisticRegression()

In [17]:
from sklearn.metrics import accuracy_score
train_prediction = model.predict(X_train)
training_data_acc = accuracy_score(train_prediction, Y_train)
print('accuracy on training data is',training_data_acc)

accuracy on training data is 0.8342245989304813

In [18]:
test_prediction = model.predict(X_test)
test_data_acc = accuracy_score(test_prediction, Y_test)
print('accuracy on test data is',test_data_acc)

accuracy on test data is 0.7619047619047619

In [19]:
input_data = (0.0200, 0.0371, 0.0428, 0.0207, 0.0954, 0.0986, 0.1539, 0.1601, 0.3109, 0.2111, 0.1609, 0.1582, 0.2238, 0.0645, 0.0660, 0.2273, 0.3100, 0.2999, 0.5078, 0.4797, 0.5783, 0.5071, 0.4328, 0.5550, 0.6711, 0.6415, 0.7104, 0.8080, 0.6791, 0.3857, 0.1307, 0.2604, 0.5121, 0.7547, 0.8537, 0.8507, 0.6692, 0.6097, 0.4943, 0.2744, 0.0510, 0.2834, 0.2825, 0.4256, 0.2641, 0.1386, 0.1051, 0.1343, 0.0383, 0.0324, 0.0232, 0.0027, 0.0065, 0.0159, 0.0072, 0.0167, 0.0180, 0.0084, 0.0090, 0.0032)
input_data_np = np.asarray(input_data)
input_data_reshaped = input_data_np.reshape(1,-1)
input_data_df = pd.DataFrame(input_data_reshaped, columns=X_train.columns)
input_prediction = model.predict(input_data_df)

if(input_prediction[0] == 'R'):
    print("The object is a Rock")
else:
    print("The object is a Mine")

The object is a Rock